/**
 * Tool Library — lookup tools from Mastercam .tooldb extracts.
 *
 * Libraries are loaded from JSON files generated by:
 *   node scripts/extract-tool-libraries.js
 *
 * Usage in DSL:
 *   findTool('haas', 'ballnose', 8)  → ToolDefinition for 8mm ballnose
 *   findTool('mazak', 'flat', 12)    → ToolDefinition for 12mm flat endmill
 */

import type { ToolDefinition } from './toolpath.js';
import haasTools from './tool-libraries/haas.json';
import mazakTools from './tool-libraries/mazak.json';

export interface LibraryTool {
  number: number;
  type: string;
  diameter: number;
  corner_radius: number;
  flute_length: number;
  overall_length: number;
  shoulder_length: number;
  flutes: number;
  shank_diameter: number;
  mfg_code: string;
}

const LIBRARIES: Record<string, LibraryTool[]> = {
  haas: haasTools as LibraryTool[],
  mazak: mazakTools as LibraryTool[],
};

/**
 * Find a tool from a named library by type and diameter.
 * Returns null if no match. If multiple matches, picks the one with the
 * longest flute length (most capable).
 */
export function findTool(
  machine: string,
  type: string,
  diameter: number,
): ToolDefinition | null {
  const lib = LIBRARIES[machine.toLowerCase()];
  if (!lib) {
    const available = Object.keys(LIBRARIES).join(', ');
    throw new Error(`Unknown tool library "${machine}". Available: ${available}`);
  }

  const matches = lib.filter(
    t => t.type === type && Math.abs(t.diameter - diameter) < 0.01,
  );

  if (matches.length === 0) return null;

  // Pick longest flute length
  const best = matches.reduce((a, b) => a.flute_length > b.flute_length ? a : b);

  return {
    name: `${machine}-${type}-D${best.diameter}`,
    type: type === 'ballnose' ? 'ballnose' : 'ballnose', // kernel only supports ballnose for now
    diameter: best.diameter,
    radius: best.diameter / 2,
    flute_length: best.flute_length,
    shank_diameter: best.shank_diameter,
  };
}

/**
 * List all tools in a library, optionally filtered by type.
 */
export function listTools(machine: string, type?: string): LibraryTool[] {
  const lib = LIBRARIES[machine.toLowerCase()];
  if (!lib) {
    const available = Object.keys(LIBRARIES).join(', ');
    throw new Error(`Unknown tool library "${machine}". Available: ${available}`);
  }
  return type ? lib.filter(t => t.type === type) : lib;
}

/** List available library names. */
export function listLibraries(): string[] {
  return Object.keys(LIBRARIES);
}
